yaml
name: Deploy to Staging Server

'on':
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging Rails Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            APP_DIR="/home/zama/sekeniror"

            echo "Deploying dev to staging"

            cd "$APP_DIR"

            git fetch origin
            git reset --hard origin/dev

            bundle install

            RAILS_ENV=staging bundle exec rails db:migrate

            sudo systemctl restart skoolswap-staging

            echo "Deployment complete"

